---

name: CI/CD Pipeline for Soulpage Frontend and Backend Deployment using Docker

on:
  push:
    branches:
      - docker

jobs:
  build-and-deploy:
    runs-on: soulpage

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image of Frontend and Push it to DockerHub
        run: |
          cd frontend
          docker build -t lahari23/soulpage:frontend-${{ github.run_number }} .
          docker push lahari23/soulpage:frontend-${{ github.run_number }}

      - name: Build Docker Image of Backend and Push it to DockerHub
        run: |
          cd backend
          docker build -t lahari23/soulpage:backend-${{ github.run_number }} .
          docker push lahari23/soulpage:backend-${{ github.run_number }}

      - name: Deploy Frontend container
        run: |
          docker image rm $(docker image ls -q)
          docker container rm -f $(docker container ls -a -q)
          docker run -d -P lahari23/soulpage:frontend-${{ github.run_number }}

      - name: Deploy Backend container
        run: | 
          docker run -d -P lahari23/soulpage:backend-${{ github.run_number }}

      - name: Deploying the applications using doker compose
        run:
         docker compose up -d && docker image ls && docker container ls -a